// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz2EWsptALDiyCthP1gCXTC_PHfj-Xa1E',
    appId: '1:140335952475:web:74db6dd770fe6ffb67857e',
    messagingSenderId: '140335952475',
    projectId: 'multiriskapp',
    authDomain: 'multiriskapp.firebaseapp.com',
    storageBucket: 'multiriskapp.firebasestorage.app',
    measurementId: 'G-VVP4WVEG6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFEDM7dYrHnLdkVbeI9O0a8ofpBPYKuM4',
    appId: '1:140335952475:android:78ed55fef9bf9a2567857e',
    messagingSenderId: '140335952475',
    projectId: 'multiriskapp',
    storageBucket: 'multiriskapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUCpBO0zjwshCD25Y8O9A4kKm0fAJiilo',
    appId: '1:140335952475:ios:d29a248bfecfcba767857e',
    messagingSenderId: '140335952475',
    projectId: 'multiriskapp',
    storageBucket: 'multiriskapp.firebasestorage.app',
    iosBundleId: 'com.example.multiriskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUCpBO0zjwshCD25Y8O9A4kKm0fAJiilo',
    appId: '1:140335952475:ios:d29a248bfecfcba767857e',
    messagingSenderId: '140335952475',
    projectId: 'multiriskapp',
    storageBucket: 'multiriskapp.firebasestorage.app',
    iosBundleId: 'com.example.multiriskapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz2EWsptALDiyCthP1gCXTC_PHfj-Xa1E',
    appId: '1:140335952475:web:3c63511072cc211867857e',
    messagingSenderId: '140335952475',
    projectId: 'multiriskapp',
    authDomain: 'multiriskapp.firebaseapp.com',
    storageBucket: 'multiriskapp.firebasestorage.app',
    measurementId: 'G-SXK1V44L3R',
  );
}
